# Access Restrictions

# The sample password below is 'insecure-pw' - do not use in production!

#admin:
#	password:	$2y$10$koBJgyhl0QgBwmiE/.MdXOXR0mrTG29bjq37VHxBdZJJTDY2GE/n2
#	groups:		admins
#	validity-period: 600


#author:
#	password:	$2y$10$Pnfo9Rp1AQxWn8MiYY./xeSQzy.zrDZZOLGOsPKt/ycakhkYjwzaK
#	groups:		editors


#user:
#	password:	$2y$10$Si6sdFALvmIS2J2XoN4EquZoAwV4nuidOIk3ukW0nqOjm4jLmnlP.
#	groups:		testgroup
