# User DB
#==========
#
#--------------------------------------------------------------------------------------
# See https://getlizzy.net/misc/access_control/ for reference
# Options:
# ========
# password:
#       A hash code of the password is stored, not the original password.
#       -> use convert tool '<url>?convert' to create hashed password.
# groups:
#       Only members of a group here get access. 
#       Predefined groups: admins, editors, fileadmins. 
#       In the sitemap file (config/sitemap.txt) pages may be designated as 
#       restricted:group
# email:
#       (optional) permits logging in withough a password: the user enters that (or 
#       the username) and Lizzy will a one-time access code to that address. Clicking 
#       on the contained link will log the user in.
# emailList:
#       (optional) points to a file containing a list of email-address. Owners of these 
#       addresses are permitted to log in using the one-time access code mechanism.
# displayName:
#       (optional) if set, that name will be shown in the webpage (e.g. in the 
#       'Logged in as…' link)
# maxSessionTime:
#       (optional), if set, it defines the time in seconds that the user can access 
#       the page without logging in again.
# accessCodeEnabled:
#       (optional) permits to disable the one-time access code mechanism for a 
#       particular user.
# accessCodeValidyTime:
#       (optional) defines the time during whith a one-time access code (or link) 
#       is valid. Maximum time possible is 60 minutes.
# accessCode:
#       (optional) a password-like string consisting of 6 uppercase letters and digits
#       (plain or hashed) that can be used to build a custom link: append to the URL
#       like a subfolder, e.g. https://getlizzy.net/mypage/U8KDF2
#       Any user who knows this link can automatically log in and access otherwise
#       restricted pages. Not very secure but convenient.
# accessCodeValidUntil:
#       (optional) defines the date and time until an accessCode (see above) expires.
# inactive:
#       (optional) If true, the owner of this account cannot log in.
#--------------------------------------------------------------------------------------


# The sample password below is 'insecure-pw' - do not use in production!

# admin:
#     password:     $2a$10$nvgug7wDF/.ErP5lVzKnY.977FaZP0kedf4UQkwk7BCpVCrgZrHD6
#     groups:       admins
#     email:        webmaster@domain.net


# author:
#     password:     $2a$10$nvgug7wDF/.ErP5lVzKnY.977FaZP0kedf4UQkwk7BCpVCrgZrHD6
#     groups:       editors
#     email:        name@domain.net


# user:
#     password:     $2a$10$nvgug7wDF/.ErP5lVzKnY.977FaZP0kedf4UQkwk7BCpVCrgZrHD6
#     groups:       members, vips
#     email:        user@domain.net
#     displayName:  John Doe

