# Settings:
# see https://getlizzy.net/ for documentation
#   in particular https://getlizzy.net/?config

# activate options by removing the leading '#'

#admin_autoAdminOnLocalhost: false                # default=true
#admin_defaultAccessLinkValidyTime: ''            # default=900
#admin_enableAccessLink: false                    # default=true
#admin_enableAutoCreateAccount: true              # default=false
#admin_enableDailyUserTask: false                 # default=true
#admin_enableEditing: true                        # default=false
#admin_hideWhileEditing: true                     # default=false
#admin_logClientAccesses: true                    # default=false
#admin_usersFile: ''                              # default=users.yaml
#admin_webmasterEmail: false                      # default=true

#class_accordiontabs: ''                          # default=accordion
#class_editable: ''                               # default=editable
#class_zoomTarget: ''                             # default=zoomTarget

#custom_computedVariablesFile: ''                 # default=user-var-defs.php
#custom_permitUserCode: true                      # default=false
#custom_permitUserVarDefs: ''                     # default=sandboxed
#custom_variables: ''                             # default=variables*.yaml

#debug_allowDebugInfo: true                       # default=false
#debug_collectBrowserSignatures: true             # default=false
#debug_errorLogging: true                         # default=false
#debug_logClientAccesses: true                    # default=false
#debug_monitorUnusedVariables: true               # default=false
#debug_showDebugInfo: true                        # default=false
#debug_showUndefinedVariables: false              # default=true
#debug_showVariablesUnreplaced: true              # default=false

#feature_autoAttrFile: true                       # default=false
#feature_autoForceBrowserCache: true              # default=false
#feature_autoLoadClassBasedModules: false         # default=true
#feature_autoLoadJQuery: true                     # default=false
#feature_cssFramework: true                       # default=false
#feature_enableSelfSignUp: true                   # default=false
#debug_forceBrowserCacheUpdate: true            # default=false
#feature_jQueryModule: ''                         # default=JQUERY
#feature_loadJQuery: true                         # default=false
#feature_pageSwitcher: true                       # default=false
#feature_quickview: true                          # default=false
#feature_register_allow: true                     # default=false
#feature_register_requireOldPW: true              # default=false
#feature_renderTxtFiles: true                     # default=false
#feature_selflinkAvoid: false                     # default=true
#feature_sitemapFromFolders: true                 # default=false
#feature_slideShowSupport: true                   # default=false
#feature_supportLegacyBrowsers: true              # default=false

#path_dataPath: ''                                # default=data/
#path_logPath: true                               # default=false
#path_pagesPath: ''                               # default=pages/
#path_stylesPath: ''                              # default=css/
#path_userCodePath: ''                            # default=code/

#site_defaultLanguage: ''                         # default=en
#site_enableCaching: true                         # default=false
#site_multiLanguageSupport: true                  # default=false
#site_pageTemplateFile: ''                        # default=page_template.html
#site_sitemapFile: ''                             # default=sitemap.txt
#site_supportedLanguages: ''                      # default=en
