# Lizzy Settings:
#   see https://getlizzy.net/site/site_configuration/ for documentation
#--------------------------------------------------------------------------

# site_timeZone:                            # set appropriate value, e.g 'Europe/Zurich' (but not a short value like 'CET')

debug_enableDevMode: true                   # => settings in config/dev-mode-config.yaml become active
debug_enableDevModeAutoOff: false           # -> if true, automatically returns to normal mode on next morning

site_supportedLanguages: en                 # supported languages, first one is default, e.g. 'de,fr,en'

#site_enableFilesCaching: true               # caching of CSS and JS files
#site_enableCaching: true                    # Caching of HTML files

#custom_permitUserCode: true                 # If true, user-provided code can be executed. And only if located in 'code/'

#site_robots: true                          # If true, Lizzy will add a meta-tag to inform search engines, not to index this site.
#site_ContentSecurityPolicy: true           # CSP: set true to activate, default is "report only" (-> reports in browser's console)

__END__

my_option: true                             # custom options available to user code (-> starting with 'my_')


#=== List of available configuration items and their default values ===========================

admin_activityLogging: true                  # If true, logs activities to file .#logs/log.txt.
admin_allowDisplaynameForLogin: false        # If true, users may log in using their "DisplayName" rather than their "UserName".
admin_autoAdminOnLocalhost: false            # If true, on local host user automatically has admin privileges without login.
admin_defaultAccessLinkValidyTime: 900       # Default Time in seconds during whith an access-link is valid.
admin_defaultGuestGroup: guest               # Name of default group for self-registration.
admin_defaultLoginValidityPeriod: 86400      # Defines how long a user can access the page since the last login.
admin_enableAccessLink: true                 # Activates one-time-access-link login mechanism.
admin_enableEditing: true                    # Enables online editing
admin_enableFileManager: false               # If true, the file-manager (upload, rename, delete) is enabled for privileged users.
admin_enableSelfSignUp: false                # If true, visitors can create a guest account on their own.
admin_enforcePasswordQuality: false          # If true, a minimum password quality is enforced when users create/change their password.
admin_minPasswordLength: 10                  # [integer] Minimum length of passwords if "admin_enforcePasswordQuality" is enabled.
admin_serviceTasks:                          # Enables and defines various service tasks.
    'daily': false,
    'onPageInit': false,
    'onPageRenderingStart': false,
    'onPageRendered': false,
    'onRequestGetArg': false,
    'dailyFilePurge': false,
admin_useRequestRewrite: true                # If true, assumes web-server supports request-rewrite (i.e. .htaccess).
admin_userAllowSelfAccessLink: false         # If true, user can create an "access-link"
admin_userAllowSelfAdmin: false              # If true, user can modify their account after they logged in

custom_permitUserCode: false                 # Only if true, user-provided code can be executed. And only if located in 'code/'
custom_permitUserInitCode: false             # Only if true, user-provided init-code can be executed. And only if located in 'code/'
custom_permitUserVarDefs: false              # Only if true, "_code/user-var-defs.php" will be executed.
custom_relatedGitProjects:                   # Git Project(s) to be included in ?gitstat command
custom_wrapperTag: section                   # The HTML tag in which MD-files are wrapped (default: section)

debug_allowDebugInfo: false                  # [false|true] If true, debugging Info can be activated: use "?debug" or set debug_showDebugInfo=true
debug_collectBrowserSignatures: false        # If true, Lizzy records browser signatures of visitors.
debug_compileScssWithLineNumbers: false      # If true, original line numbers are added as comments to compiled CSS."
debug_debugLogging: false                    # Enable or disabling logging.
debug_enableDevMode: false                   # [false|true] Enables devolepment mode
debug_enableDevModeAutoOff: false            # [false|true] If true, devolepment mode is automatically turned of the next morning
debug_errorLogging: false                    # Enable or disabling logging.
debug_forceBrowserCacheUpdate: false         # If true, the browser is forced to ignore the cache and reload css and js resources on every time.
debug_forceDebugMode: false                  # [false|true] If true, forces debug mode, even if not logged in (debug mode normally activated by"?debug"
debug_logClientAccesses: false               # If true, Lizzy records visits (IP-addresses and browser/os types).
debug_monitorUnusedVariables: false          # [false|true] If true, Lizzy keeps track of variable usage. Initialize tracking with url-arg "?reset"
debug_showDebugInfo: false                   # If true, debugging info is appended to the page (prerequisite: debug_allowDebugInfo=true and localhost or logged in as editor/admin)
debug_showUndefinedVariables: false          # If true, all undefined static variables (i.e. obtained from yaml-files) are marked.
debug_showVariablesUnreplaced: false         # If true, all static variables (i.e. obtained from yaml-files) are render as {{ name }}.

feature_ImgDefaultMaxDim: 1600x1200          # Defines the max dimensions ("WxH") to which Lizzy automatically converts images which it finds in the pages folders.
feature_SrcsetDefaultStepSize: 250           # Defines the step size when Lizzy creates srcsets for images.
feature_autoConvertLinks: false              # If true, automatically converts text that looks like links to HTML-links (i.e. <a> tags).
feature_autoLoadClassBasedModules: true      # If true, automatically loads modules that are invoked by applying classes, e.g. .editable
feature_autoLoadJQuery: true                 # If true, jQuery will be loaded automatically (even if not initiated explicitly by macros)
feature_enableIFrameResizing: false          # If true, includes js code required by other pages to iFrame-embed this site
feature_enableScssInPageFolder: false        # If true, Lizzy checks for .scss files in page folder and compiles them to .css. Alternatively use "enableScssInPageFolder" in Frontmatter of specific pages.
feature_externalLinksInNewWin: false         # If true, automatically makes links open in new window for all external links (i.e. starting with http).
feature_filterRequestString: true            # If true, permits only regular text in requests. Special characters will be discarded.
feature_frontmatterCssLocalToSection: false  # If true, all CSS rules in Frontmatter will be modified to apply only to the current section (i.e. md-file content).
feature_jQueryModule: JQUERY                 # Specifies the jQuery Version to be loaded: one of [ JQUERY | JQUERY1 | JQUERY2 | JQUERY3 ], default is jQuery 3.x.
feature_lateImgLoading: false                # If true, enables general use of lazy-loading of images
feature_pageSwitcher: false                  # If true, code will be added to support page switching (by arrow-keys or swipe gestures)
feature_preloadLoginForm: false              # If true, code for login popup is preloaded and opens without page load.
feature_quickview: true                      # If true, enables automatic Quickview of images
feature_renderTxtFiles: false                # If true, all .txt files in the pages folder are rendered (in <pre>-tags, i.e. as is). Otherwise they are ignored.
feature_replaceNLandTabChars: false          # If true, "\n" and "\t" will be replaced to corresponding control characters.
feature_screenSizeBreakpoint: 480            # [px] Determines the point where Lizzy switches from small to large screen mode.
feature_selflinkAvoid: false                 # If true, the nav-link of the current page is replaced with a local page link (to satisfy a accessibility requirement).
feature_sitemapFromFolders: false            # If true, the sitemap will be derived from the folder structure under pages/, rather than the config/sitemap.yaml file.
feature_supportLegacyBrowsers: false         # If true, jQuery 1 is loaded in case of legacy browsers.
feature_touchDeviceSupport: true             # If true, Lizzy supports swipe gestures etc. on touch devices.

path_logPath: .#logs/                        # [true|Name] Name of folder to which logging output will be sent. Or "false" for disabling logging.
path_stylesPath: css/                        # Name of folder in which style sheets reside
path_userCodePath: code/                     # Name of folder in which user-provided PHP-code must reside.

site_ContentSecurityPolicy: report           # [true,report,false] Enables "Content Security Policy (CSP)" for scripts embedded in pages. (Default: report)
site_allowFrameAncestors: 'self'             # Defines who can import pages from this site via <frame>. Default: 'self'. Add URL to allow others.
site_allowInsecureConnectionsTo: 192.*       # [domain(s)] Permit login over insecure connections to webhost on stated domain/ip-address.
site_cacheResetIntervall: 24                 # (number of hours) Defines the interval after which the cache shall be reset. When that happens,page requests will build up the cache again.
site_compiledStylesFilename: __styles.css    # Name of style sheet containing collection of compiled user style sheets
site_dataPath: data/                         # Path to data/ folder.
site_devDataPath:                            # Activates a mechanism that, in dev-mode, switches /Lizzy-Dev/CSP/data/ to given destination. Thus, you can savely develop and test in dev-mode without overwriting hot data. Hint: set site_dataPath to "../db/".
site_devDataPathPattern: /-                  # Regex-pattern to match against appRoot path to identify, whether we are running on a dev site, e.g. "/(dev|-)". Default: "/-"
site_enableAllowOrigin: false                # Set to "*" or explicitly to a domain to allow other websites to include pages of this site.
site_enableCaching: false                    # If true, Lizzy's caching mechanism is activated.
site_enableFilesCaching: false               # If true, Lizzy's module caching mechanism is activated. I.e. CSS and JS files are collected and delivered to browser in just two requests.
site_enableMdCaching: false                  # If true, Lizzy's MD caching mechanism is activated. (not fully implemented yet)
site_enableRelLinks: true                    # If true, injects "rel links" into header, e.g. "<link rel='next' title='Next' href='...'>"
site_extractSelector: body main              # [selector] Lets an external js-app request an extract of the web-page
site_localeCodes: en_GB,de_DE,fr_FR,it_IT    # Defines prefered locale codes for supported languages. If not found, Lizzy assumes "xy_XY".
site_pageTemplateFile: page_template.html    # Name of file that will be used as the template. Must be located in 'config/'
site_robots: false                           # If true, Lizzy will add a meta-tag to inform search engines, not to index this site.
site_sitemapFile: sitemap.txt                # Name of file that defines the site structure. Build hierarchy simply by indenting.
site_supportedLanguages: en                  # Defines which languages will be supported: comma-separated list of language-codes. E.g. "en, de, fr" (first elem => default lang)
site_timeZone: auto                          # Name of timezone, e.g. "UTC" or "CET". If auto, attempts to set it automatically.


