# Settings:
# see https://getlizzy.net/ for documentation
#   in particular https://getlizzy.net/?config

# activate options by removing the leading '#'
#--------------------------------------------------------------------------

admin_autoAdminOnLocalhost: true                 # default=false

#admin_activityLogging: false                     # default=true
#admin_allowDisplaynameForLogin: true             # default=false
#admin_autoAdminOnLocalhost: true                 # default=false
#admin_defaultAccessLinkValidyTime: ''            # default=900
#admin_defaultGuestGroup: ''                      # default=guest
#admin_defaultLoginValidityPeriod: ''             # default=86400
#admin_enableAccessLink: false                    # default=true
#admin_enableDailyUserTask: false                 # default=true
#admin_enableEditing: false                       # default=true
#admin_hideWhileEditing: true                     # default=false
#admin_logClientAccesses: true                    # default=false
#admin_useRequestRewrite: false                   # default=true
#admin_userAllowSelfAdmin: false                  # default=true
#admin_webmasterEmail: false                      # default=true

#custom_permitUserCode: true                      # default=false
#custom_permitUserInitCode: true                  # default=false
#custom_permitUserVarDefs: ''                     # default=sandboxed
#custom_wrapperTag: true                          # default=false

#debug_allowDebugInfo: true                       # default=false
#debug_autoForceBrowserCache: true                # default=false
#debug_collectBrowserSignatures: true             # default=false
#debug_compileScssWithLineNumbers: true           # default=false
#debug_errorLogging: true                         # default=false
#debug_forceBrowserCacheUpdate: true              # default=false
#debug_logClientAccesses: true                    # default=false
#debug_monitorUnusedVariables: true               # default=false
#debug_showDebugInfo: true                        # default=false
#debug_showUndefinedVariables: true               # default=false
#debug_showVariablesUnreplaced: true              # default=false
#debug_suppressInsecureConnectWarning: true       # default=false

#feature_ImgDefaultMaxDim: ''                     # default=1600x1200
#feature_SrcsetDefaultStepSize: ''                # default=300
#feature_autoLoadClassBasedModules: false         # default=true
#feature_autoLoadJQuery: false                    # default=true
#feature_cssFramework: ''                         # default=
#feature_enableAllowOrigin: true                  # default=false
#feature_enableSelfSignUp: true                   # default=false
#feature_filterRequestString: true                # default=false
#feature_jQueryModule: ''                         # default=JQUERY
#feature_lateImgLoading: true                     # default=false
#feature_loadFontAwesome: true                    # default=false
#feature_pageSwitcher: true                       # default=false
#feature_preloadLoginForm: true                   # default=false
#feature_quickview: false                         # default=true
#feature_renderTxtFiles: true                     # default=false
#feature_screenSizeBreakpoint: ''                 # default=480
#feature_selflinkAvoid: false                     # default=true
#feature_sitemapFromFolders: true                 # default=false
#feature_slideShowSupport: true                   # default=false
#feature_supportLegacyBrowsers: true              # default=false
#feature_touchDeviceSupport: false                # default=true

#path_logPath: ''                                 # default=.#logs/
#path_pagesPath: ''                               # default=pages/
#path_stylesPath: ''                              # default=css/
#path_userCodePath: ''                            # default=code/

#site_compiledStylesFilename: ''                  # default=__styles.css
#site_dataPath: ''                                # default=data/
#site_defaultLanguage: ''                         # default=en
#site_defaultLocale: ''                           # default=en_US
#site_enableCaching: true                         # default=false
#site_extractSelector: ''                         # default=body main
#site_multiLanguageSupport: true                  # default=false
#site_pageTemplateFile: ''                        # default=page_template.html
#site_robots: true                                # default=false
#site_sitemapFile: ''                             # default=sitemap.txt
#site_supportedLanguages: ''                      # default=
#site_timeZone: true                              # default=false
