# Settings:
# see https://getlizzy.net/site/ for documentation

defaultLanguage: en     // use ISO 639-1 Language Code
caching: false
pageSwitcher: true
permitUserVarDefs: true
permitUserCode: true
loadJQuery: true
quickview: true
enableEditing: true
errorLogging: true
loadJQuery: true
cssFramework:  w3.css // purecss // bootstrap // purecss
#supportLegacyBrowsers: false

__END__

