# Dev Mode Config Options
#========================

admin_autoAdminOnLocalhost: true
debug_compileScssWithLineNumbers: true
debug_errorLogging: true

#debug_forceBrowserCacheUpdate: true

#my_option: true       # custom options available to user code

