# Transvar Definition File
# -- generic definitions


#--- Login Link ----------------------------------
space: "&nbsp;&nbsp;"

vgap: "<div class='vgap' style='margin:1em 0;'>&nbsp;</div>\n"

clear: '<div style="clear:both;"></div>'

user_icon: '<img src="~sys/rsc/user.svg" />'
#user_icon: "&#128100;"


#--- Forms -----------------------------------------------
Username:
    de: Benutzername
    en: Username

Password:
    de: Kennwort
    en: Password


cancel:
    de: abbrechen
    en: cancel
Cancel: 
    de: Abbrechen
    en: Cancel

Done:
    de: Beenden
    en: Done

Save:
    de: Speichern
    en: Save

Submit:
    de: Absenden
    en: Submit
    
submit:
    de: absenden
    en: send

Confirm:
    de: Bestätigen
    en: Confirm
confirm:
    de: bestätigen
    en: confirm

Continue:
    de: Weiter
    en: Continue
Continue_:
    de: Weiter...
    en: Continue...

File to upload:
    de: Datei(en) hochladen
    en: Upload file(s)

Uploaded file list:
    de: "Hochgeladene Dateien:"
    en: "Uploaded files:"


Loading: '<img class="lzy-loading-spinner" src="~sys/rsc/loader.gif" alt="" />'

#--- Links -------------------------------
opens mail app: 
    de: 'Öffnet in Mail-Anwendung'
    en: opens in your mail-application

opens in new win:
    de: Öffnet in neuem Fester
    en: Opens in new window



#--- Navigation --------------------------
lzy-nav-elem-button:
    de: Untermenü öffnen mit Leertaste
    en: Open sub-menu using space key


#--- Language Selection ------------------
select langauge:
    de: Sprache auswählen 
    en: Select language

select de: "<img src='~sys/rsc/de.png' class='lang-icon' alt='' /><span class='invisible'>Deutsch</span>"
select en: "<img src='~sys/rsc/en.png' class='lang-icon' alt='' /><span class='invisible'>English</span>"


    
# --- Login ------------------------------
lzy-onetimelogin-email-info-title:
    de: "Hilfe: Zugang per E-Mail"
    en: "Help on access by e-mail"


lzy-onetimelogin-email-info-text:
    de: "<p>Geben Sie Ihre <strong>E-Mail-Adresse</strong> ein. <br>&rarr; Sie erhalten dann eine Mail mit einem Zugangs-Link. Klicken Sie auf diesen Link. So sind Sie automatisch im Browser angemeldet.</p>
    <p>Der Link enthält einen <strong>Zugangs-Code</strong>. Dieser Code ist nur ein einziges Mal und nur während 15 Minuten gültig.</p>
    <p>Damit dies funktioniert, muss Ihre E-Mail-Adresse bei uns registriert sein. Kontaktieren Sie den {{ Webmaster }}, falls dies nicht der Fall ist.</p>"
    en: "<p>Enter your <strong>e-mail address</strong>.<br>&rarr; You will then get an e-mail containing a link. Click on that link to open the web-page you requested.</p>
    <p>This Link contains an <strong>access code</strong>. This code is only valid one time and within the next 15 minutes.</p>
    <p>Note: for this to work your e-mail address must be registered. Contact the {{ Webmaster }} if that is not the case.</p>"

lzy-login-username-prompt:
    de: E-Mail Adresse (oder Benutzername)
    en: E-mail address (or username)

info-lzy-onetimelogin-title:

lzy-login-username-info-text:
    de: "Falls Sie Benutzernamen und Kennwort kennen, können Sie sich hier anmelden. Geben Sie in das folgende Feld Ihren Benutzernamen ein. Dies entspricht normalerweise Ihrer E-Mail Adresse."
    en: "If you know your username and password you can log in now. Enter your username in the following field. Usually your e-mail address is used as your username."

lzy-login-password-prompt:
    de: Kennwort
    en: Password

lzy-login-username-info-title:
    de: Hilfe
    en: Help

lzy-login-password-info:
    de: "Geben Sie hier Ihr Kennwort ein. Verwenden Sie &#34;Anmelden ohne Kennwort&#34;, falls Sie ihr Kennwort nicht kennen (oder dieses nicht funktionierte)."
    en: "Enter your password here. Use <strong>login by e-mail</strong> if you don&#39;t have your password available (if that didn&#39;t work)."

login-email-prompt:
    de: Ihre E-Mail Adresse
    en: Your e-mail address

lzy-login-send:
    de: Anmelden
    en: Login

Login comment:
    de: Um diese Seite zu sehen, benötigen Sie gültige Zugangsdaten.
    en: To see this page you need valid credentials.

Logout:
    de: Abmelden
    en: Logout

Login failed:
    de: Benutzername oder Kennwort passen nicht.<br />Bitte versuchen Sie es erneut.
    en: User unknown or password incorrect.<br />Please try again.

Insufficient privileges:
    de: Ihre Zugangsberechtigung genügt nicht für diese Seite.
    en: Your user privileges are insufficient to view this page.

Err empty username:
    de: Bitte geben Sie Ihren Benutzernahmen ein
    en: Please enter your user name

Err empty password:
    de: Bitte geben Sie Ihr Kennwort ein
    en: Please enter your password

LoginLink:
    de: Anmelden
    en: Login

Logged in as:
    de: Angemeldet als
    _: Logged in as
#    de: Angemeldet als
#    en: Logged in as

User account:
    de: Benutzerkonto
    _: User account

Open user popup:
    de: Benutzerkonto
    _: User account

User account of:
    de: Angemeldet als
    _: Logged in as
#    de: Benutzerkonto von
#    _: User account of

page requires login:
    de: "Sie müssen angemeldet sein, um die gesuchte Seite sehen zu können."
    en: "You need to be logged in to see the requested page."


validity-period expired:
    de: Bitte melden Sie sich erneut an, da zu viel Zeit verstrichen ist seit Ihrer letzten Anmeldung.
    en: Please login again, session time has expired.

Or request one-time-access-link:
    de: Oder einen Link für einmaligen Zugang anfordern.
    en: "Or request a one-time access link."

email required for one-time-access-link:
    de: Eine E-Mail-Adresse wird benötigt, um den einmaligen Zugangs-Link zu senden.
    en: "We need your e-mail address to send you a one-time access link."

lzy-login-successful:
    de: 'Sie sind jetzt angemeldet.'
    _: 'You are successfully logged in now.'

lzy-logout-successful:
    de: 'Sie sind jetzt abgemeldet.'
    _: 'You are successfully logged out now.'

lzy-login-failed:
    de: 'Die Anmeldung ist fehlgeschlagen.'
    _: 'Login failed.'


#login with password:
#    de: Anmeldung mit <br>Kennwort
#    en: Login with <br>password

#login without password:
#    de: Anmeldung ohne <br>Kennwort
#    en: Login without <br>password

#login with choice:
#    de: Anmeldung
#    en: Log in

#login with password:
#    de: mit <br>Kennwort
#    en: by <br>password
#
#login without password:
#    de: ohne <br>Kennwort
#    en: by <br>e-mail


#info-onetimelogin-title:
#    de: "Hilfe: Zugang per E-Mail"
#    en: "Help on access by e-mail"

#info-onetimelogin-text:
#    de: "<p>Geben Sie Ihre <strong>E-Mail-Adresse</strong> ein. <br>&rarr; Sie erhalten dann eine Mail mit einem Zugangs-Link. Klicken Sie auf diesen Link. So sind Sie automatisch im Browser angemeldet.</p>
#    <p>Der Link enthält einen <strong>Zugangs-Code</strong>. Dieser Code ist nur ein einziges Mal und nur während 15 Minuten gültig.</p>
#    <p>Damit dies funktioniert, muss Ihre E-Mail-Adresse bei uns registriert sein. Kontaktieren Sie den {{ Webmaster }}, falls dies nicht der Fall ist.</p>"
#    en: "<p>Enter your <strong>e-mail address</strong>.<br>&rarr; You will then get an e-mail containing a link. Click on that link to open the web-page you requested.</p>
#    <p>This Link contains an <strong>access code</strong>. This code is only valid one time and within the next 15 minutes.</p>
#    <p>Note: for this to work your e-mail address must be registered. Contact the {{ Webmaster }} if that is not the case.</p>"

un-pw-login-info:
    de: "Geben Sie Ihren Benutzernamen ein.<br>Kontaktieren Sie den {{ Webmaster }}, falls Sie noch keine Zugangsdaten besitzen."
    en: "Enter your username.<br>Contact the {{ Webmaster }} if you don&#39;t have credentials for this website."

#login-password-info:
login-password-login-info:
    de: "Geben Sie Ihr Kennwort ein.Kontaktieren Sie den {{ Webmaster }}, falls Sie das Kennwort vergessen haben oder ein sonstiges Problem aufgetreten ist."
    en: "Enter your password.<br>Contact the {{ Webmaster }} if you forgot your password or some other problem has come up."

info-password-login-title:
    de: 'Hilfe: zum Kennwort'
    en: 'Help on password'




//maillink Webmaster: "{{ concat('forgot password1', webmaster-email,'?subject=',login-problems,'&body=%0a%0aURL:%20',pageUrl, '\'\>Webmaster</a>') }}"

#forgot password:
#    de: "<a href='mailto:webmaster-email'>Kennwort funktioniert nicht oder vergessen...</a>"
#    en: "<a href='mailto:webmaster-email'>Password not working or forgotten...</a>"
#login-problems:
#    de: Probleme beim Anmelden
#    en: Login problems
    
#forgot password1:
#    de: "<a href='mailto:"
#    en: "<a href='mailto:"
#
#forgot password2:
#    de: "'>Kennwort funktioniert nicht oder vergessen...</a>"
#    en: "'>Password not working or forgotten...</a>"

    
#Login show password:
#    de: Kennwort offen anzeigen
#    en: Show password in plain text

#Login show password:
#    de: anzeigen
#    en: show

Login-Email:
    de: Ihre E-Mail Adresse
    en: Your e-mail address

onetime-link-send:
    de: Absenden
    en: Send

Err empty username or email:
    de: Geben Sie Ihren Benutzernamen oder Ihre E-Mail-Adresse ein.
    en: Enter your username or e-mail address.

Err empty email:
    de: Sie müssen eine E-Mail Adresse eingeben
    en: You need to enter an e-mail address



    
#Email Access-Link Subject:
#    de: "Zugangslink für"
#    en: "Access Link for"
#
#Email Access-Link1:
#    de: "Guten Tag\n\nHier ist der Zugangs-Link, mit dem Sie die Webseite ansprechen können: \n\n\t"
#    en: "Hello\n\nHere is the link with which you can access the webpage: \n\n\t"
#    
#Email Access-Link2:
#    de: "\n\nSie können auch den folgenden Code ins Eigabefeld in der Website eintragen:"
#    en: "\n\nOr you can enter the following code into the entry field in the webpage:"
#
#Email Access-Link3:
#    de: "\n\nBitte beachten Sie, dass der Link und der Code nur einmal innerhalb der nächsten 15 Minuten funktioniert.\n\nBeste Grüsse, Ihre Lizzy\n"
#    en: "\n\nPlease note that this link and this code only works once within the next 15 minutes.\n\nCheers, \nLizzy\n "
#
#



Your Profile:
    de: Profil bearbeiten
    en: Edit Profile



#--- Insecure Connection ----------------------------
Warning insecure connection:
    de: "Achtung: die Verbindung zum Webhost ist nicht gesichert (https). Sie können sich deshalb nicht anmelden."
    en: "Warning: your connection to this webhost is insecure (https). For this reason you cannot login."

Please switch to:
    de: Bitte wechseln Sie auf
    en: Please switch to






#--- Misc ------------------------------------------
Page:
    de: Seite
    en: Page
    
page:
    de: Seite
    en: page
    
of:
    de: von
    en: of
    
Unknown Page Title:
    de: Unbekannte Seite
    en: Unknown Page

Page unknown:
    de: Die gesuchte Seite existiert nicht in dieser Website.
    en: Sorry, the page you asked for could not be found within this website.

lzy-popup-close-button: '✕'
#lzy-lightbox-close-button: '☒'
#lzy-popup-close-button: '☒'


#--- Editing -------------------------------------
turn edit mode on:
    de: Seite bearbeiten
    en: Edit page


# Macro Editable()
'lzy-editable-temporarily-locked': 
    de: 'Dieses Feld ist momentan gesperrt, weil es gerade von jemand anderem bearbeitet wird.\n\nBitte versuchen Sie es in ein paar Minuten nochmals. (Seite muss dann neu geladen werden!)'
    en: 'This field is currently locked because somebody else is editing it.\n\nPlease try again in a few minutes. (Remember to reload the page when trying again.)'

#--- Forms ----------------------------------------
lzy-form-data-received-ok:
    de: "Ihre Eingaben wurden abgespeichert. Besten Dank."
    en: "Your entries have been saved successfully. Thank you."

lzy-form-feedback-local: "<strong>Feedback on localhost only:</strong>"

lzy-form-continue:
    de: Weiter...
    en: Continue...

